# Версия операционной системы Windows
image: Visual Studio 2019

# Версия Python
environment:
  matrix:
    - PYTHON: "C:\\Python39"
      PYTHON_VERSION: "3.9"

# Установка зависимостей (библиотек) из requirements.txt
install:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python --version
  - python -m pip install --upgrade pip --disable-pip-version-check
  - pip install --upgrade setuptools wheel
  - pip install numpy<2.0
  - pip install --prefer-binary -r requirements.txt

# Команды для запуска приложения
build_script:
  - python app.py


# deploy:
#   provider: heroku
#   app: your-heroku-app-name
#   api_key:
#     secure: your-encrypted-heroku-api-key
