# Версия операционной системы Windows
image: Visual Studio 2019

# Версия Python
environment:
  PYTHON: "C:\\Python310"
  PYTHON_VERSION: "3.10.9"

# Установка зависимостей (библиотек) из requirements.txt
install:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install matplotlib --upgrade
  - ps: Install-Product python $env:PYTHON_VERSION x64

# Команды для запуска приложения
build_script:
  - python app.py  # Запуск приложения


# deploy:
#   provider: heroku
#   app: your-heroku-app-name
#   api_key:
#     secure: your-encrypted-heroku-api-key
