# Версия операционной системы Windows
image: Visual Studio 2019

# Версия Python
environment:
  PYTHON: "C:\\Python310"
  PYTHON_VERSION: "3.10.9"

# Установка зависимостей (библиотек) из requirements.txt
install:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python --version
  - python -m pip install --upgrade pip
  - ps: Install-Product python $env:PYTHON_VERSION x64
  - pip install --upgrade setuptools wheel
  - pip install --prefer-binary -r requirements.txt

# Команды для запуска приложения
build_script:
  - python app.py


# deploy:
#   provider: heroku
#   app: your-heroku-app-name
#   api_key:
#     secure: your-encrypted-heroku-api-key
