# Среда сборки
image: Visual Studio 2022

# Версия Python
environment:
  matrix:
    - PYTHON: "C:\\Python311"
      PYTHON_VERSION: "3.11"

# Установка зависимостей (библиотек) из requirements.txt
install:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python --version
  - python -m pip install --upgrade pip --disable-pip-version-check
  - pip install --upgrade setuptools wheel
  - pip install --prefer-binary -r requirements.txt

# Команды для запуска приложения
build_script:
  - python app.py
